# Generated by Django 2.2 on 2019-05-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='second_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
